[package]
name = "pyo3_smd_example"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21.2", features = ["multiple-pymethods"] }
pyo3_special_method_derive = "0.1.1"

[lib]
name = "pyo3_smd_example"
crate-type = ["cdylib"]
doc = false
